### PR TITLE
Add & update tests

### PR DESCRIPTION
**Pull request by Senorsen**
- Add (provider)netease-cloud-music-test
- Update QQMusicTest

---
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/20)

### CODE REVIEW

**Comment by richard1122** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 41 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/20#-KIs08PHe4jsmyJWQeVm:-KIs08PHe4jsmyJWQeVn:1095022078) ([raw file](https://github.com/gyrosworkshop/wukong/blob/07b4fcddd0e7df38085521a5289b72283de317b4/README.md#L41)):*
> ```Markdown
>     length: number
>     /**
>     * bitrate: number like 96000 (represents 96kpbs), 192000, 320000, etc.
> ```

我有个疑问，为啥需要把比特率传给前端？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/20)*

**Comment by richard1122** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 41 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/20#-KIs08PHe4jsmyJWQeVm:-KIs0JEcLnCwksuMDfM7:2107878258) ([raw file](https://github.com/gyrosworkshop/wukong/blob/07b4fcddd0e7df38085521a5289b72283de317b4/README.md#L41)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 我有个疑问，为啥需要把比特率传给前端？
</details>
因为qq music这里不太容易得到比特率，而且好像前端知道了也没啥用。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/20)*

**Comment by richard1122** [comment]
Reviewed 1 of 5 files at r1, 1 of 2 files at r2.
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/test/QQMusicTest.ts, line 20 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/20#-KIs0XafIawKN2kyi5qu:-KIs0XafIawKN2kyi5qv:-819121495) ([raw file](https://github.com/gyrosworkshop/wukong/blob/9250a3b13604cd336b80c8ca64c43e18a1f788da/src/test/QQMusicTest.ts#L20)):*
> ```XML
>     })
>     describe('getSongInfo', () => {
>         it('演员', async (done) => {
> ```

这里为什么要改？我这个测试就是异步的啊？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/20)*

**Comment by richard1122** [comment]
Reviewed 1 of 5 files at r1, 1 of 2 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/20)*

**Comment by Senorsen** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 41 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/20#-KIs08PHe4jsmyJWQeVm:-KIs0wvsXXvAD-gmcoBf:-781975290) ([raw file](https://github.com/gyrosworkshop/wukong/blob/07b4fcddd0e7df38085521a5289b72283de317b4/README.md#L41)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 因为qq music这里不太容易得到比特率，而且好像前端知道了也没啥用。
</details>
这个我一开始是考虑：如果一次搜索有多个provider返回结果，bitrate之类的东西可以用作排序，只是一个微小的想法，所以当初加上了。后来我发现netease-cloud-music这边获取bitrate也比较麻烦……

---

*[src/test/QQMusicTest.ts, line 20 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/20#-KIs0XafIawKN2kyi5qu:-KIs0nGdN6IDgGLn3i-T:-1611364954) ([raw file](https://github.com/gyrosworkshop/wukong/blob/9250a3b13604cd336b80c8ca64c43e18a1f788da/src/test/QQMusicTest.ts#L20)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 这里为什么要改？我这个测试就是异步的啊？
</details>
是这样的，mocha从某一版本开始，支持直接使用return promise，不需调用done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/20)*

**Comment by richard1122** [comment]
Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/20)*

**Pull request merged**
