### PR TITLE
改善wyyyy搜索速度；获取更高品质音乐；下架检测筛除

### PR DESCRIPTION
**Pull request by Senorsen**
使用了一点加密算法来通过id计算出封面、音乐文件地址

---
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/87)

### CODE REVIEW

**Comment by richard1122** [comment]
Reviewed 3 of 5 files at r1.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/87)*

**Comment by Senorsen** [comment]
test ci

**Comment by Senorsen** [comment]
test ci

**Comment by richard1122** [comment]
Reviewed 1 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/87)*

**Pull request merged**
