### PR TITLE
Models

### PR DESCRIPTION
**Pull request by Leeleo3x**
Create channel model and user model.

---
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/8)

### CODE REVIEW

**Comment by richard1122** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/models/Channel.ts, line 5 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp1qUlHH6P4FMOoDiL:-KIp1qUlHH6P4FMOoDiM:-1801077496) ([raw file](https://github.com/gyrosworkshop/wukong/blob/ebdd63492e8b749e3a6404cc7f9c27ebfee03b1f/src/models/Channel.ts#L5)):*
> ```XML
> export default class Channel {
>   // TODO(Leeleo3x): The type should be replaced by interface.
>   delegate: any;
> ```

delegate为啥不写具体的类型？

---

*[src/models/Channel.ts, line 14 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp2FavRMFL-WJdfhQy:-KIp2FavRMFL-WJdfhQz:1389932993) ([raw file](https://github.com/gyrosworkshop/wukong/blob/ebdd63492e8b749e3a6404cc7f9c27ebfee03b1f/src/models/Channel.ts#L14)):*
> ```XML
>   }
> 
>   join(user: User) {
> ```

为啥好几个函数的返回值都没有标注类型？

---

*[src/models/Channel.ts, line 31 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp220-vB4uy-gdbyIc:-KIp220-vB4uy-gdbyId:-1537296793) ([raw file](https://github.com/gyrosworkshop/wukong/blob/ebdd63492e8b749e3a6404cc7f9c27ebfee03b1f/src/models/Channel.ts#L31)):*
> ```XML
>     setTimeout(() => {
>       this.startCheckUserStatus(song);
>     }, song.length);
> ```

song.length 是 seconds, setTimeout接受 ms 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by Leeleo3x** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/models/Channel.ts, line 5 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp1qUlHH6P4FMOoDiL:-KIp2k6zRgQnoB8mWgJ3:372536228) ([raw file](https://github.com/gyrosworkshop/wukong/blob/ebdd63492e8b749e3a6404cc7f9c27ebfee03b1f/src/models/Channel.ts#L5)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> delegate为啥不写具体的类型？
</details>
因为还没实现。。。所以就先Any了。。。

---

*[src/models/Channel.ts, line 14 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp2FavRMFL-WJdfhQy:-KIp2u7hbw7gmTdiPBqF:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/ebdd63492e8b749e3a6404cc7f9c27ebfee03b1f/src/models/Channel.ts#L14)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 为啥好几个函数的返回值都没有标注类型？
</details>
Done.

---

*[src/models/Channel.ts, line 31 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp220-vB4uy-gdbyIc:-KIp2vb_TbAUVl__KIC0:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/ebdd63492e8b749e3a6404cc7f9c27ebfee03b1f/src/models/Channel.ts#L31)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> song.length 是 seconds, setTimeout接受 ms 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by richard1122** [comment]
Reviewed 4 of 9 files at r1, 1 of 1 files at r3.
Review status: 5 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by richard1122** [comment]
Review status: 5 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/models/Channel.ts, line 18 \[r4\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp5Kl4bXp-ukEfK7ub:-KIp5Kl4bXp-ukEfK7uc:-1503239124) ([raw file](https://github.com/gyrosworkshop/wukong/blob/ea93067d75a0d1b886097b25944a406c5b2ae2d9/src/models/Channel.ts#L18)):*
> ```XML
>   leave(user: User): void {
>     var index = this.userList.indexOf(user);
>     this.userList.splice(index, 1);
> ```

indexOf找不到时候返回 -1, 会导致 splice 删除最后一个对象

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by Leeleo3x** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/models/Channel.ts, line 18 \[r4\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp5Kl4bXp-ukEfK7ub:-KIp6Zn7KL8LEhBTXwO9:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/ea93067d75a0d1b886097b25944a406c5b2ae2d9/src/models/Channel.ts#L18)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> indexOf找不到时候返回 -1, 会导致 splice 删除最后一个对象
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by richard1122** [comment]
Reviewed 2 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by richard1122** [comment]
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/models/Channel.ts, line 51 \[r5\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp7A4sU7ipESV5ip8w:-KIp7A4sU7ipESV5ip8x:-522859781) ([raw file](https://github.com/gyrosworkshop/wukong/blob/d8f57ca40535ef55de5fff4e124d8684020ebd05/src/models/Channel.ts#L51)):*
> ```XML
>   }
> 
>   nextSongRecursion(count: number): Wukong.ISong {
> ```

这个函数是不是应该 private ？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by richard1122** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/models/User.ts, line 6 \[r5\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp7aIBrCjWalJshNHX:-KIp7aIBrCjWalJshNHY:-855238265) ([raw file](https://github.com/gyrosworkshop/wukong/blob/d8f57ca40535ef55de5fff4e124d8684020ebd05/src/models/User.ts#L6)):*
> ```XML
> 
>   // Seconds
>   private _elapsedTime: number
> ```

这个为啥要加下划线？。。

---

*[src/models/User.ts, line 11 \[r5\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp83-Mu2LOx2ziDZjI:-KIp83-Mu2LOx2ziDZjJ:-863832562) ([raw file](https://github.com/gyrosworkshop/wukong/blob/d8f57ca40535ef55de5fff4e124d8684020ebd05/src/models/User.ts#L11)):*
> ```XML
>   lastUpdateTime: number
> 
>   listenOnlyMode: boolean = false
> ```

这个变量是怎么工作的？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by Leeleo3x** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/models/Channel.ts, line 51 \[r5\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp7A4sU7ipESV5ip8w:-KIp8nfKwrTxXUuZCFCR:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/d8f57ca40535ef55de5fff4e124d8684020ebd05/src/models/Channel.ts#L51)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 这个函数是不是应该 private ？
</details>
Done.

---

*[src/models/User.ts, line 6 \[r5\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp7aIBrCjWalJshNHX:-KIp8Y_uzuVRqbjJ7Y2I:-1529165010) ([raw file](https://github.com/gyrosworkshop/wukong/blob/d8f57ca40535ef55de5fff4e124d8684020ebd05/src/models/User.ts#L6)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 这个为啥要加下划线？。。
</details>
因为那个elapsedTime被setter和getter占用了

---

*[src/models/User.ts, line 11 \[r5\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp83-Mu2LOx2ziDZjI:-KIp8fCKHtC6LzzPeGGo:1165567866) ([raw file](https://github.com/gyrosworkshop/wukong/blob/d8f57ca40535ef55de5fff4e124d8684020ebd05/src/models/User.ts#L11)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 这个变量是怎么工作的？
</details>
这是一个public member 所以直接赋值就可以了

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by richard1122** [comment]
Reviewed 2 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by Leeleo3x** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/models/Channel.ts, line 51 \[r5\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp7A4sU7ipESV5ip8w:-KIp9NaXP8D9-3M4Tp-G:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/d8f57ca40535ef55de5fff4e124d8684020ebd05/src/models/Channel.ts#L51)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by richard1122** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by Leeleo3x** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/models/Channel.ts, line 51 \[r5\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp7A4sU7ipESV5ip8w:-KIpAOf9qm87tKrDQqKQ:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/d8f57ca40535ef55de5fff4e124d8684020ebd05/src/models/Channel.ts#L51)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by Leeleo3x** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/models/Channel.ts, line 51 \[r5\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp7A4sU7ipESV5ip8w:-KIpAQIwdJ_y6QMc71Ys:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/d8f57ca40535ef55de5fff4e124d8684020ebd05/src/models/Channel.ts#L51)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by Leeleo3x** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/models/Channel.ts, line 51 \[r5\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KIp7A4sU7ipESV5ip8w:-KIpBKQPUw2FibUfmK9q:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/d8f57ca40535ef55de5fff4e124d8684020ebd05/src/models/Channel.ts#L51)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Comment by richard1122** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)*

**Pull request merged**
