### PR TITLE
加回网易云音乐provider

### PR DESCRIPTION
**Pull request by Senorsen**
- 添加服务器端默认配置文件，允许cdn和api中转、端口指定
- 改善搜索逻辑，增加搜索和音乐信息的缓存

---
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/86)

### CODE REVIEW

**Comment by Leeleo3x** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/controllers/ProviderController.ts, line 17 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86#-KLBubleCCQOmvAhaZXR:-KLBubleCCQOmvAhaZXS:-1805842180) ([raw file](https://github.com/gyrosworkshop/wukong/blob/75aaccd8798d35eed21f836efa3e329f8ad2c046/src/controllers/ProviderController.ts#L17)):*
> ```XML
>         serverConfig.provider.forEach((providerName: string) => {
>             switch (providerName) {
>                 case 'netease-cloud-music':
> ```

use NeteaseCloudMusicProvider.providerName

---

*[src/controllers/ProviderController.ts, line 20 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86#-KLBuj9TdRgffmUwe-dP:-KLBuj9TdRgffmUwe-dQ:678021867) ([raw file](https://github.com/gyrosworkshop/wukong/blob/75aaccd8798d35eed21f836efa3e329f8ad2c046/src/controllers/ProviderController.ts#L20)):*
> ```XML
>                     this.providerList.set('netease-cloud-music', new NeteaseCloudMusicProvider())
>                     break
>                 case 'QQMusic':
> ```

same

---

*[src/providers/netease-cloud-music.ts, line 12 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86#-KLBv2KT6hGe-QxLHWSw:-KLBv2KT6hGe-QxLHWSx:-483575128) ([raw file](https://github.com/gyrosworkshop/wukong/blob/75aaccd8798d35eed21f836efa3e329f8ad2c046/src/providers/netease-cloud-music.ts#L12)):*
> ```XML
>     static providerName = 'netease-cloud-music'
>     static apiPrefix = serverConfig['netease-cloud-music-api-prefix']
>     static binCdn = serverConfig['netease-cloud-music-bin-cdn']
> ```

Lint. Move static members to the top of scope.

---

*[src/providers/netease-cloud-music.ts, line 75 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86#-KLBvRs8fBMGcdBmCpVz:-KLBvRs8fBMGcdBmCpW-:1342107224) ([raw file](https://github.com/gyrosworkshop/wukong/blob/75aaccd8798d35eed21f836efa3e329f8ad2c046/src/providers/netease-cloud-music.ts#L75)):*
> ```XML
>         })
> //        console.log(JSON.stringify(this.convertToSong(resObject.songs)[0], null, 4))
>         const song = this.convertToSong(resObject.songs)[0]
> ```

What if the request failed here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86)*

**Comment by Senorsen** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/providers/netease-cloud-music.ts, line 75 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86#-KLBvRs8fBMGcdBmCpVz:-KLBwKdWJ0Q5XmhHF6NA:1668063348) ([raw file](https://github.com/gyrosworkshop/wukong/blob/75aaccd8798d35eed21f836efa3e329f8ad2c046/src/providers/netease-cloud-music.ts#L75)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> What if the request failed here?
</details>
It will fail this search event. Should I use a fail-safe mechanism?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86)*

**Comment by Leeleo3x** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/providers/netease-cloud-music.ts, line 75 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86#-KLBvRs8fBMGcdBmCpVz:-KLBxxY9VNT_kncerQjo:187163873) ([raw file](https://github.com/gyrosworkshop/wukong/blob/75aaccd8798d35eed21f836efa3e329f8ad2c046/src/providers/netease-cloud-music.ts#L75)):*
<details><summary><i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>
> It will fail this search event. Should I use a fail-safe mechanism?
</details>
You need either make it safe here or make it safe while calling this method in searchSongs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86)*

**Comment by Senorsen** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/providers/netease-cloud-music.ts, line 12 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86#-KLBv2KT6hGe-QxLHWSw:-KLBzOpGt-5xqHenRgf_:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/75aaccd8798d35eed21f836efa3e329f8ad2c046/src/providers/netease-cloud-music.ts#L12)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> Lint. Move static members to the top of scope.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86)*

**Comment by Senorsen** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/providers/netease-cloud-music.ts, line 75 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86#-KLBvRs8fBMGcdBmCpVz:-KLC-ZdBAUt1IVW16yGs:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/75aaccd8798d35eed21f836efa3e329f8ad2c046/src/providers/netease-cloud-music.ts#L75)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> You need either make it safe here or make it safe while calling this method in searchSongs.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86)*

**Comment by Leeleo3x** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86)*

**Comment by Leeleo3x** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/providers/netease-cloud-music.ts, line 57 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86#-KLCBvCRgfmyMNTs-ga5:-KLCBvCRgfmyMNTs-ga6:-967749802) ([raw file](https://github.com/gyrosworkshop/wukong/blob/66a00a946ffbf5be30102bdf331506fa9bf9b473/src/providers/netease-cloud-music.ts#L57)):*
> ```XML
>                 }
>             })
>             let songList = await Promise.all<Wukong.ISong>(resObject.result.songs.map((o: any) => this.getSongInfo(o.id.toString())))
> ```

I don't think one failed request should make all results dropped. But it really depends. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86)*

**Comment by Leeleo3x** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/86#-:-KLCCujaRFFuJGW0iXqN:1417088721)*

**Pull request merged**
