### PR TITLE
add typings to deps

### PR DESCRIPTION
**Pull request by Qusic**
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/61)

### CODE REVIEW

**Comment by Senorsen** [comment]
test this

**Comment by Qusic** [comment]
啥意思？。。

**Comment by Senorsen** [comment]
This will trigger a rebuild in my jenkins-ci.

**Comment by richard1122** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/61)*

**Pull request merged**
