### PR TITLE
Add ILyric (lyrics of song)

### PR DESCRIPTION
**Pull request by Senorsen**
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/95)

### CODE REVIEW

**Comment by Leeleo3x** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/providers/netease-cloud-music.ts, line 109 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/95#-KMCS4cgONb15zelo0Fc:-KMCS4cgONb15zelo0Fd:-1059218498) ([raw file](https://github.com/gyrosworkshop/wukong/blob/b877e65e98f5668329f668b438c2d0f6463104b9/src/providers/netease-cloud-music.ts#L109)):*
> ```XML
>     private songInfoCache: Map<string, Wukong.ISong> = new Map()
>     private songSearchCache: Map<string, Wukong.ISong[]> = new Map()
>     private songLyricCache: Map<string, any> = new Map()
> ```

Why any here?

---

*[src/providers/netease-cloud-music.ts, line 333 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/95#-KMCSwkjfFeIMY0m7XoZ:-KMCSwkjfFeIMY0m7Xo_:-1368423512) ([raw file](https://github.com/gyrosworkshop/wukong/blob/b877e65e98f5668329f668b438c2d0f6463104b9/src/providers/netease-cloud-music.ts#L333)):*
> ```XML
>             }
>         } else {
>             throw new Error('lrc interface ret code not 200')
> ```

这里的行为和上面的尽量一致，比如都反回空数组，或者都抛异常。

如果不是致命的错误的话我觉得只在这里log一下error然后返回空数组比较好，毕竟上面接住了这个异常也干不了啥。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/95)*

**Comment by Senorsen** [comment]
Review status: 9 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/providers/netease-cloud-music.ts, line 109 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/95#-KMCS4cgONb15zelo0Fc:-KMN0TDQWexlqjwilFYg:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/b877e65e98f5668329f668b438c2d0f6463104b9/src/providers/netease-cloud-music.ts#L109)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> Why any here?
</details>
Done.

---

*[src/providers/netease-cloud-music.ts, line 333 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/95#-KMCSwkjfFeIMY0m7XoZ:-KMN0YXcm0_psDw-6aEk:549080281) ([raw file](https://github.com/gyrosworkshop/wukong/blob/b877e65e98f5668329f668b438c2d0f6463104b9/src/providers/netease-cloud-music.ts#L333)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 这里的行为和上面的尽量一致，比如都反回空数组，或者都抛异常。
> 
> 如果不是致命的错误的话我觉得只在这里log一下error然后返回空数组比较好，毕竟上面接住了这个异常也干不了啥。
</details>
但是上面返回空数组是因为确定没有歌词，这边是因为有异常，我觉得情况可能有所不同。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/95)*

**Comment by Leeleo3x** [comment]
*[src/providers/netease-cloud-music.ts, line 333 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/95#-KMCSwkjfFeIMY0m7XoZ:-KMQMon9nVOrF6jyglUY:20854119) ([raw file](https://github.com/gyrosworkshop/wukong/blob/b877e65e98f5668329f668b438c2d0f6463104b9/src/providers/netease-cloud-music.ts#L333)):*
<details><summary><i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>
> 但是上面返回空数组是因为确定没有歌词，这边是因为有异常，我觉得情况可能有所不同。
</details>
我的意思是，这里面的异常即使有了异常对返回值其实是不影响的，我们都应该向前端返回一个空的数组，所以可以直接在这里log 错误信息，然后返回一个空数组回去。或者在这里进行重试。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/95)*

**Comment by Senorsen** [comment]
Reviewable seems offline; done.

**Comment by Senorsen** [comment]
Review status: 6 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/providers/netease-cloud-music.ts, line 333 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/95#-KMCSwkjfFeIMY0m7XoZ:-KMUE8_wc4mxo8NdDY57:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/b877e65e98f5668329f668b438c2d0f6463104b9/src/providers/netease-cloud-music.ts#L333)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 我的意思是，这里面的异常即使有了异常对返回值其实是不影响的，我们都应该向前端返回一个空的数组，所以可以直接在这里log 错误信息，然后返回一个空数组回去。或者在这里进行重试。
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/95)*

**Comment by Leeleo3x** [comment]
Reviewed 3 of 4 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/95)*

**Pull request merged**
