### PR TITLE
fix play

### PR DESCRIPTION
**Pull request by Qusic**
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/70)

### CODE REVIEW

**Comment by richard1122** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/ChannelController.ts, line 133 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/70#-KKwwdQyBzUnpfeldVOq:-KKwwdQyBzUnpfeldVOr:-1916237098) ([raw file](https://github.com/gyrosworkshop/wukong/blob/667a2f921c37c05880226651cf3e153072264d24/src/controllers/ChannelController.ts#L133)):*
> ```XML
> 
>     private async startMonitoringChannel(channel: Channel, song: Wukong.ISong): Promise<void> {
>         await Utilities.sleep(channel.currentSong.length * 1000)
> ```

这里单位就是毫秒啊，难道 wyyyy 那边返回的是ms ? @senorsen 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/70)*

**Comment by richard1122** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/70)*

**Comment by Senorsen** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/ChannelController.ts, line 133 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/70#-KKwwdQyBzUnpfeldVOq:-KKwxFVZ4KJWIeqBG7vV:-212041332) ([raw file](https://github.com/gyrosworkshop/wukong/blob/01751231e9bdcc3d76e9b001e2001577f55ff3b4/src/controllers/ChannelController.ts#L133)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 这里单位就是毫秒啊，难道 wyyyy 那边返回的是ms ? @senorsen 
</details>
呃，毫秒不就是ms么

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/70)*

**Comment by richard1122** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/ChannelController.ts, line 133 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/70#-KKwwdQyBzUnpfeldVOq:-KKwxNWmltR0kUqk9wHa:-91510002) ([raw file](https://github.com/gyrosworkshop/wukong/blob/01751231e9bdcc3d76e9b001e2001577f55ff3b4/src/controllers/ChannelController.ts#L133)):*
<details><summary><i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>
> 呃，毫秒不就是ms么
</details>
我的意思是qq音乐这里的length 单位是 s， 这个api接受的是 ms，所以要*1000， 所以是不是wyyy的length是 ms？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/70)*

**Comment by Qusic** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/ChannelController.ts, line 133 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/70#-KKwwdQyBzUnpfeldVOq:-KKwxc-D_exIyIzYKNeu:6012410) ([raw file](https://github.com/gyrosworkshop/wukong/blob/01751231e9bdcc3d76e9b001e2001577f55ff3b4/src/controllers/ChannelController.ts#L133)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 我的意思是qq音乐这里的length 单位是 s， 这个api接受的是 ms，所以要*1000， 所以是不是wyyy的length是 ms？
</details>
是的

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/70)*

**Comment by Senorsen** [comment]
test ci

**Comment by richard1122** [comment]
Reviewed 1 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/70)*

**Comment by Senorsen** [comment]
test ci

**Comment by Senorsen** [comment]
test ci

**Comment by Senorsen** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/70)*

**Pull request merged**
