### PR TITLE
Disallow single user joinin multiple channels

### PR DESCRIPTION
**Pull request by richard1122**
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/5)

### CODE REVIEW

**Comment by aoli-al** [comment]
:lgtm:

---

Reviewed 5 of 7 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/5#-:-KQyhXTSBwv5NpwlSvhU:bnfp4nl)_

**Comment by aoli-al** [comment]
_[src/Wukong/Services/ChannelManager.cs, line 29 [r2]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/5#-KQyhhGyM56qGPu_bi4Z:-KQyhhGyM56qGPu_bi4_:b2w6jpj) ([raw file](https://github.com/gyrosworkshop/wukong/blob/f1122f5132a808bbe2fb36057bc7f8f50cc8856b/src/Wukong/Services/ChannelManager.cs#L29)):_

> ``` Smalltalk
>         {
>             if (channelId == Storage.Instance.GetChannelByUser(userId)?.Id) return;
>             Leave(userId);
> ```

Leave 的逻辑是不是应该放在controller里面，或者这里改名叫JoinAndLeavePreviousChannel

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/5)_

**Comment by richard1122** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/Wukong/Services/ChannelManager.cs, line 29 [r2]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/5#-KQyhhGyM56qGPu_bi4Z:-KQyim8tajGOQmsZ5RBq:bsqa28a) ([raw file](https://github.com/gyrosworkshop/wukong/blob/f1122f5132a808bbe2fb36057bc7f8f50cc8856b/src/Wukong/Services/ChannelManager.cs#L29)):_
<details><summary>

<i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>



> Leave 的逻辑是不是应该放在controller里面，或者这里改名叫JoinAndLeavePreviousChannel
> </details>
> 好，感觉应该改个名字。。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/5)_

**Comment by Senorsen** [comment]
Reviewed 4 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/5)_

**Pull request merged**
