### PR TITLE
使用typescript，移除babel。

### PR DESCRIPTION
**Pull request by richard1122**
使用 jake ，tslint，tsc 等等。。

---
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/6)

### CODE REVIEW

**Comment by richard1122** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 25 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/6#-KIlinvpsTBA11cXJaHr:-KIlinvpsTBA11cXJaHs:-1451129327) ([raw file](https://github.com/gyrosworkshop/wukong/blob/8b8bb8576ae9d9d62218d616d28d5a08d1fbb9c1/package.json#L25)):*
> ```JSON
>   "homepage": "https://github.com/gyrosworkshop/Wukong#readme",
>   "devDependencies": {
>     "jake": "latest",
> ```

为啥在这里用jake？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/6)*

**Comment by richard1122** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 25 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/6#-KIlinvpsTBA11cXJaHr:-KIlisVn6RqvNAoIlNw5:-748347380) ([raw file](https://github.com/gyrosworkshop/wukong/blob/8b8bb8576ae9d9d62218d616d28d5a08d1fbb9c1/package.json#L25)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 为啥在这里用jake？
</details>
Jake 挺好用的，ts 的项目就在用。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/6)*

**Comment by Senorsen** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 25 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/6#-KIlinvpsTBA11cXJaHr:-KIlqfMwrN-cdln2m2eX:-1221830102) ([raw file](https://github.com/gyrosworkshop/wukong/blob/8b8bb8576ae9d9d62218d616d28d5a08d1fbb9c1/package.json#L25)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> Jake 挺好用的，ts 的项目就在用。
</details>
为啥用latest最新版？会不会有cli的API变更之类的

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/6)*

**Comment by richard1122** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 25 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/6#-KIlinvpsTBA11cXJaHr:-KImei13Lw_yQORXSf2w:-694660333) ([raw file](https://github.com/gyrosworkshop/wukong/blob/8b8bb8576ae9d9d62218d616d28d5a08d1fbb9c1/package.json#L25)):*
<details><summary><i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>
> 为啥用latest最新版？会不会有cli的API变更之类的
</details>
我改成具体版本号吧

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/6)*

**Comment by Senorsen** [comment]
Looks good

<details><summary><i>Previously, mention-bot wrote…</i></summary>
> By analyzing the blame information on this pull request, we identified @Senorsen to be a potential reviewer
</details>


---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/6#-:-KImxYPhgMXlmrorsGHn:1739129486)*

**Comment by Senorsen** [comment]
Reviewed 16 of 17 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/6)*

**Pull request merged**
