### PR TITLE
Channel router

### PR DESCRIPTION
**Pull request by Leeleo3x**
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/21)

### CODE REVIEW

**Comment by Leeleo3x** [comment]
This pr is for backend structure review.

<details><summary><i>Previously, mention-bot wrote…</i></summary>
> By analyzing the blame information on this pull request, we identified @richard1122 and @Senorsen to be potential reviewers
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-:-KIs5iWdQv6EgcI5-jSi:-1206712175)*

**Comment by Senorsen** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIs6EtyK4Y8FMs5vbpB:-KIs6EtyK4Y8FMs5vbpC:1303957024) (no related file):*
一言不合

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by Senorsen** [comment]
rebuild

**Comment by Leeleo3x** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIs6EtyK4Y8FMs5vbpB:-KItnJCmVvZ5Fb-41k_o:1150141063) (no related file):*
<details><summary><i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>
> 一言不合
</details>
Ready for review now.

---

*[src/models/Channel.ts, line 28 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KItniXJYAtDXU3xmL5s:-KItniXJYAtDXU3xmL5t:-607567643) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/models/Channel.ts#L28)):*
> ```XML
>   }
> 
>   async startCheckUserStatus() {
> ```

I'm not really sure about the return type of this method. Promise<void> is not working.  Any idea about this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/controllers/ChannelController.ts, line 42 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIu76XKFUKpcrBjUoGD:-KIu76XKFUKpcrBjUoGE:-1229208609) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/controllers/ChannelController.ts#L42)):*
> ```XML
>   private async startMonitorChannel(channel: Channel, song: Wukong.ISong): Promise<void> {
>     let sleep = new Promise((r) => setTimeout(r, channel.currentSong.length * 1000))
>     await sleep
> ```

sleep 是个函数，需要 await sleep()

---

*[src/models/Channel.ts, line 28 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KItniXJYAtDXU3xmL5s:-KIu7cvTbQsRkTdkPSD2:-66420049) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/models/Channel.ts#L28)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> I'm not really sure about the return type of this method. Promise<void> is not working.  Any idea about this?
</details>
这里看起来似乎是一个 Promise<void>

---

*[src/models/Storage.ts, line 7 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIu8MuYfQTJPEyCb4d_:-KIu8MuZaoZY1DEduo8m:-3398908) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/models/Storage.ts#L7)):*
> ```XML
> export default class Storage {
>   static channels: Map<string, Channel> = new Map()
>   static users: Map<string, User> = new Map()
> ```

这两个是不是应该private？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/models/Channel.ts, line 28 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KItniXJYAtDXU3xmL5s:-KIu9bZiTMODpO9Y5B7_:1018442648) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/models/Channel.ts#L28)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 这里看起来似乎是一个 Promise<void>
</details>
Promise<void> 怎么void不见了 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
Reviewed 1 of 7 files at r1, 1 of 6 files at r3.
Review status: 2 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
Review status: 2 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/controllers/ChannelController.ts, line 42 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIu76XKFUKpcrBjUoGD:-KIuBlSd_3Yw6JZCTkly:-1740074141) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/controllers/ChannelController.ts#L42)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> sleep 是个函数，需要 await sleep()
</details>
据说不需要

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
Review status: 2 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[types/type.d.ts, line 33 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIuBsiJliMqBLtDimhB:-KIuBsiJliMqBLtDimhC:-1116490268) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/types/type.d.ts#L33)):*
> ```XML
>   }
>   export interface IChannelRouter {
>     broadcastEvent(channelId: string, event: any): void
> ```

只有 broadcast 的话没法分出这个是给当前用户发的还是给所有用户发的，有时候可能不需要给所有用户发。比如在某个用户刚刚加入这个room，需要开始播放时候，只给他playing就可以了。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
Review status: 2 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[types/type.d.ts, line 33 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIuCQ0oA-HyHif5L736:-KIuCQ0oA-HyHif5L737:551434023) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/types/type.d.ts#L33)):*
> ```XML
>   }
>   export interface IChannelRouter {
>     broadcastEvent(channelId: string, event: any): void
> ```

应该要发送 eventName + data. 也就是 event:string, data:any. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by Leeleo3x** [comment]
Review status: 2 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/models/Channel.ts, line 28 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KItniXJYAtDXU3xmL5s:-KIu5MHpAyrg53T5kSOq:-1423828887) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/models/Channel.ts#L28)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> Promise<void> 怎么void不见了 
</details>
I've tried both Promise and Promise<void> and unfortunately, neither of them was working.

---

*[src/models/Storage.ts, line 7 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIu8MuYfQTJPEyCb4d_:-KIuC6PNP4XkDEWEOXOn:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/models/Storage.ts#L7)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 这两个是不是应该private？
</details>
Done.

---

*[types/type.d.ts, line 33 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIuBsiJliMqBLtDimhB:-KIuCRXRdZ9qPVSic6UG:-457099185) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/types/type.d.ts#L33)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 只有 broadcast 的话没法分出这个是给当前用户发的还是给所有用户发的，有时候可能不需要给所有用户发。比如在某个用户刚刚加入这个room，需要开始播放时候，只给他playing就可以了。
</details>
嗯，这个方法只是用于broadcast整个channel的用户，之后还应该需要添加其他的方法。

---

*[types/type.d.ts, line 33 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIuCQ0oA-HyHif5L736:-KIuCa7pMHi0mtxaGFoK:-205042335) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/types/type.d.ts#L33)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 应该要发送 eventName + data. 也就是 event:string, data:any. 
</details>
嗯。。。不太了解api是什么样的，所以就先放了any。。。欢迎修改

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
Review status: 2 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controllers/ChannelController.ts, line 16 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIuCmwU_P2sDF3yXtQe:-KIuCmwU_P2sDF3yXtQf:-1767917437) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/controllers/ChannelController.ts#L16)):*
> ```XML
>       oldChannel.leave(user)
>     }
>     channel.join(user)
> ```

Storage 的 channel, user 都会抛异常，要看情况捕获一下。。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by Leeleo3x** [comment]
Review status: 2 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[src/controllers/ChannelController.ts, line 16 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIuCmwU_P2sDF3yXtQe:-KIuD6AcJdjJkS76DsIw:1398379992) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/controllers/ChannelController.ts#L16)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> Storage 的 channel, user 都会抛异常，要看情况捕获一下。。
</details>
233333 要不别抛异常了。。。console.log一下就好了。。。

---

*[src/controllers/ChannelController.ts, line 42 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIu76XKFUKpcrBjUoGD:-KIuDCpueI0aqDLkCKx9:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/controllers/ChannelController.ts#L42)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 据说不需要
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
Review status: 2 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[types/type.d.ts, line 33 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIuCQ0oA-HyHif5L736:-KIuD-pqqLf4PY5QigAp:-580054082) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/types/type.d.ts#L33)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 嗯。。。不太了解api是什么样的，所以就先放了any。。。欢迎修改
</details>
我的意思是 应该broadcast 事件和数据，现在是直接broadcast了事件，没有数据。 所以应该用  
broadcastEvent(channelId: string, event: string, data: any) 这个原形。 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
Review status: 2 of 8 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/routers/ChannelRouter.ts, line 16 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIuDFQdIA6JZDvbE1n-:-KIuDFQdIA6JZDvbE1n0:1112429130) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/routers/ChannelRouter.ts#L16)):*
> ```XML
>   // TODO(Leeleo3x): Provide event interface
>   broadcastEvent(channelId: string, event: any) {
>     this.io.to(channelId).emit(event)
> ```

这里要调用这个： socket.emit('an event', { some: 'data' }); 前面是 event name， 后面是 data

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
Review status: 2 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/controllers/ChannelController.ts, line 16 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIuCmwU_P2sDF3yXtQe:-KIuDydGeXVbfESeQ81P:-269155120) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/controllers/ChannelController.ts#L16)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 233333 要不别抛异常了。。。console.log一下就好了。。。
</details>
也可以。。。。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by Leeleo3x** [comment]
Review status: 2 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/controllers/ChannelController.ts, line 16 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIuCmwU_P2sDF3yXtQe:-KIuHq5W-heZAPFQGBkB:311794919) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/controllers/ChannelController.ts#L16)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 也可以。。。。
</details>
Will be fixed in following prs.

---

*[src/models/Channel.ts, line 28 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KItniXJYAtDXU3xmL5s:-KIuHocaTwxNDsdI1N85:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/models/Channel.ts#L28)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> I've tried both Promise and Promise<void> and unfortunately, neither of them was working.
</details>
Done.

---

*[src/routers/ChannelRouter.ts, line 16 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIuDFQdIA6JZDvbE1n-:-KIuHnMosEbWnolGh4pw:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/routers/ChannelRouter.ts#L16)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 这里要调用这个： socket.emit('an event', { some: 'data' }); 前面是 event name， 后面是 data
</details>
Done.

---

*[types/type.d.ts, line 33 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIuCQ0oA-HyHif5L736:-KIuHmeSlfnD5DMyoKlK:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/types/type.d.ts#L33)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 我的意思是 应该broadcast 事件和数据，现在是直接broadcast了事件，没有数据。 所以应该用  
> broadcastEvent(channelId: string, event: string, data: any) 这个原形。 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by Leeleo3x** [comment]
Review status: 2 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/controllers/ChannelController.ts, line 16 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KIuCmwU_P2sDF3yXtQe:-KIuI6HM4QIIyKYCeTtY:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/controllers/ChannelController.ts#L16)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> Will be fixed in following prs.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
Reviewed 1 of 7 files at r1, 1 of 1 files at r4, 4 of 4 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
Reviewed 1 of 4 files at r5, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/models/Channel.ts, line 28 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KItniXJYAtDXU3xmL5s:-KIuZUkpnPbiBZbpBPwt:5946601) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/models/Channel.ts#L28)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> Done.
</details>
好！

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by Leeleo3x** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/models/Channel.ts, line 28 \[r3\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-KItniXJYAtDXU3xmL5s:-KIuZYij_erQZZhobaxG:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/a91ef817643eed89073d6d59125ad7eda550ed85/src/models/Channel.ts#L28)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 好！
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21)*

**Comment by richard1122** [comment]
:lgtm:

<details><summary><i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>
> rebuild
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/21#-:-KIu_8pMZ3R8rEUooWGI:1417088721)*

**Pull request merged**
