### PR TITLE
Fix indent

### PR DESCRIPTION
**Pull request by richard1122**
一不小心多提交了一个，一定要先看 https://github.com/gyrosworkshop/Wukong/pull/34

---
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/35)

### CODE REVIEW

**Comment by Leeleo3x** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/ChannelController.ts, line 58 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/35#-KJ6YnD8cVVC9OzXOcT2:-KJ6YnD8cVVC9OzXOcT3:1982285571) ([raw file](https://github.com/gyrosworkshop/wukong/blob/06e17b2d43814efe64436e2a468e247822a102b8/src/controllers/ChannelController.ts#L58)):*
> ```XML
>         await channel.startCheckUserStatus()
>         if (song !== channel.currentSong)
>             return this.startPlayNextSong(channel)
> ```

额。。。这种语法我是坚决不接受的。。。
我接受 if () foo()
或着 
if() {
    foo()
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/35)*

**Comment by Senorsen** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/ChannelController.ts, line 58 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/35#-KJ6YnD8cVVC9OzXOcT2:-KJ6Z5ig4xjkhRKq0IwN:1535430281) ([raw file](https://github.com/gyrosworkshop/wukong/blob/06e17b2d43814efe64436e2a468e247822a102b8/src/controllers/ChannelController.ts#L58)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 额。。。这种语法我是坚决不接受的。。。
> 我接受 if () foo()
> 或着 
> if() {
>     foo()
> }
</details>
leo的dm好丑呀（
```
if () {
    foo()
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/35)*

**Comment by Senorsen** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/35)*

**Comment by Leeleo3x** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/35)*

**Comment by richard1122** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/ChannelController.ts, line 58 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/35#-KJ6YnD8cVVC9OzXOcT2:-KJ8mce8mFRLeaAXR1q0:-383890149) ([raw file](https://github.com/gyrosworkshop/wukong/blob/06e17b2d43814efe64436e2a468e247822a102b8/src/controllers/ChannelController.ts#L58)):*
<details><summary><i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>
> leo的dm好丑呀（
> ```
> if () {
>     foo()
> }
> ```
</details>
改成了一行的形式。。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/35)*

**Comment by Leeleo3x** [comment]
:lgtm:

<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> #### Fix indent
> 
> 一不小心多提交了一个，一定要先看 https://github.com/gyrosworkshop/Wukong/pull/34
> 
> 
> 
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/35#-:-KJ8sfRuIDSExJmCr2yf:1417088721)*

**Comment by Senorsen** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/35)*

**Pull request merged**
