### PR TITLE
Use ConcurrentDictionary correctly.

### PR DESCRIPTION
**Pull request by richard1122**
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/8)

### CODE REVIEW

**Comment by Senorsen** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/Wukong/Services/Storage.cs, line 27 [r1]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KQykHbosMeAJSAKTH9P:-KQykHbpjHOjqjAabKj1:b-wr2lrm) ([raw file](https://github.com/gyrosworkshop/wukong/blob/466a2af9d1b292a949b61df05c48e185014ce840/src/Wukong/Services/Storage.cs#L27)):_

> ``` Smalltalk
>         }
> 
>         public Channel GetOrCreateChannel(string channelId, ISocketManager socketManager, IProvider provider)
> ```

我有个微小的疑问，这边为什么需要传入socketManager以及上边为什么要用Lazy，而不是启动时注入一个单例的Storage？

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)_

**Comment by richard1122** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/Wukong/Services/Storage.cs, line 27 [r1]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KQykHbosMeAJSAKTH9P:-KQykta0oUncIM_mC-Nw:b-fy0l9m) ([raw file](https://github.com/gyrosworkshop/wukong/blob/466a2af9d1b292a949b61df05c48e185014ce840/src/Wukong/Services/Storage.cs#L27)):_
<details><summary>

<i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>



> 我有个微小的疑问，这边为什么需要传入socketManager以及上边为什么要用Lazy，而不是启动时注入一个单例的Storage？
> </details>
> 因为 channel 创建时候需要 socketManager.

Lazy可以第一次用到时候再初始化

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)_

**Comment by Senorsen** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/Wukong/Services/Storage.cs, line 27 [r1]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KQykHbosMeAJSAKTH9P:-KQyl62WACyas2PcgzuB:b-teh93j) ([raw file](https://github.com/gyrosworkshop/wukong/blob/466a2af9d1b292a949b61df05c48e185014ce840/src/Wukong/Services/Storage.cs#L27)):_
<details><summary>

<i>Previously, richard1122 (richard) wrote…</i></summary>



> 因为 channel 创建时候需要 socketManager.
> 
> Lazy可以第一次用到时候再初始化
> </details>
> 我可能不是很了解具体情况，不过我觉得在这里，一开始就初始化相对于延迟实例化不是更方便么，且还能使用现成的单例机制及对象注入，你们怎么看？

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)_

**Comment by richard1122** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/Wukong/Services/Storage.cs, line 27 [r1]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-KQykHbosMeAJSAKTH9P:-KQymgVi6N9Bc1dVjblO:b4qk53b) ([raw file](https://github.com/gyrosworkshop/wukong/blob/466a2af9d1b292a949b61df05c48e185014ce840/src/Wukong/Services/Storage.cs#L27)):_
<details><summary>

<i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>



> 我可能不是很了解具体情况，不过我觉得在这里，一开始就初始化相对于延迟实例化不是更方便么，且还能使用现成的单例机制及对象注入，你们怎么看？
> </details>
> 的确可以改成单例的依赖注入，你可以再开个PR

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)_

**Comment by Senorsen** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8)_

**Comment by Senorsen** [comment]
@richard1122 merge conflict

---

Review status: 1 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-:-KQynhOyxhmbOfwAb5pj:bkugsam)_

**Comment by Senorsen** [comment]
conflict solved

---

Reviewed 2 of 4 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/8#-:-KQyr7cKdl7ctyadMI2o:buej69a)_

**Pull request merged**
