### PR TITLE
minor tweak.

### PR DESCRIPTION
**Pull request by richard1122**
一个礼拜前写的，忘了到底在干啥了。

---
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/62)

### CODE REVIEW

**Comment by Leeleo3x** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/controllers/ProviderController.ts, line 31 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/62#-KKPoTDJfwrQm22S2-xM:-KKPoTDJfwrQm22S2-xN:-553809054) ([raw file](https://github.com/gyrosworkshop/wukong/blob/fccf723199e96f9afd8a0c0dd97e8202c5bd042e/src/controllers/ProviderController.ts#L31)):*
> ```XML
> 
>     async serverSongList(songs: Wukong.IClientSong[]): Promise<Wukong.ISong[]> {
>         return await Promise.all<Wukong.ISong>(songs.map(it => this.providerList.get(it.siteId).getSongInfo(it.songId)))
> ```

感觉这个可以分成几行来写。。。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/62)*

**Comment by richard1122** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/ProviderController.ts, line 31 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/62#-KKPoTDJfwrQm22S2-xM:-KKc2JhM-8C2bw_8Yh99:1328703875) ([raw file](https://github.com/gyrosworkshop/wukong/blob/fccf723199e96f9afd8a0c0dd97e8202c5bd042e/src/controllers/ProviderController.ts#L31)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 感觉这个可以分成几行来写。。。
</details>
分成了两行，不能更多了。。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/62)*

**Comment by richard1122** [comment]
这个pr主要修复了以下问题：

* 当新用户加入时channel没有音乐在播放，则直接触发play操作，不会发送nextsong
* nextSong应该是channel_event而不是user_event
* startPlayingNextSong对于目前没有音乐时不能正确开始
* songs 事件写错了
* 补全了首次进入时搜索、同步播放列表并进行播放的测试。

**Comment by richard1122** [comment]
目前代码有些问题，主要是channel的很多函数调用会造成channel的状态改变，但是却没有在controller中有足够的体现，导致这个调用有没有副作用不明确，channel数据与实际逻辑可能会不一致。最好需要简单的重构一下。 @Leeleo3x

**Comment by Leeleo3x** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controllers/ChannelController.ts, line 22 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/62#-KKdGKnHKxIrdkXOcBVj:-KKdGKnHKxIrdkXOcBVk:2080165963) ([raw file](https://github.com/gyrosworkshop/wukong/blob/59dbe8c8559abf109c1b527e9d4660075383c10f/src/controllers/ChannelController.ts#L22)):*
> ```XML
>         user.gravatar = info.gravatar || undefined
>         user.listenOnlyMode = info.listenOnlyMode
>         user.finished = true
> ```

不如把默认值改成true？或者把 user.finished = channel.isChennelIdle() 放到join前面。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/62)*

**Comment by Leeleo3x** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/controllers/ChannelController.ts, line 22 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/62#-KKdGKnHKxIrdkXOcBVj:-KKdwQWun1GmQETfwTKV:1890825877) ([raw file](https://github.com/gyrosworkshop/wukong/blob/59dbe8c8559abf109c1b527e9d4660075383c10f/src/controllers/ChannelController.ts#L22)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 不如把默认值改成true？或者把 user.finished = channel.isChennelIdle() 放到join前面。
</details>
啊。。。不能。。。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/62)*

**Pull request merged**
