### PR TITLE
add mocha, chai. qqmusic provider.

### PR DESCRIPTION
**Pull request by richard1122**
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/17)

### CODE REVIEW

**Comment by Senorsen** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/providers/QQMusic.ts, line 18 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/17#-KIriN01KhrAtu7lkI2g:-KIriN01KhrAtu7lkI2h:-358419658) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7a55f03f693403e1a485986c1b5f9b324f533bdb/src/providers/QQMusic.ts#L18)):*
> ```XML
>         const baseInfo = await this.getBaseInfo(songId)
>         song.album = baseInfo.albumname
>         song.artist = baseInfo.singer.map((it: any) => it.name).join(',')
> ```

半角逗号（, ）后边加个空格吧

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/17)*

**Comment by Senorsen** [comment]
Reviewed 5 of 8 files at r1.
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[package.json, line 7 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/17#-KIrjuRuP-S4vfBzTDxK:-KIrjuRuP-S4vfBzTDxL:-1360847824) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7a55f03f693403e1a485986c1b5f9b324f533bdb/package.json#L7)):*
> ```JSON
>   "main": "index.js",
>   "scripts": {
>     "test": "npm run build && mocha -t 5000",
> ```

要不要把build和test分开，test时只运行mocha就可以了？

---

*[src/test/QQMusicTest.ts, line 26 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/17#-KIrk5lLPL3dJ6sTrZBO:-KIrk5lLPL3dJ6sTrZBP:-1798045595) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7a55f03f693403e1a485986c1b5f9b324f533bdb/src/test/QQMusicTest.ts#L26)):*
> ```XML
>                 done()
>             } catch(err) {
>                 console.error(err)
> ```

这样遇错是不是就没有done，会超时才能结束？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/17)*

**Comment by Senorsen** [comment]
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/test/QQMusicTest.ts, line 9 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/17#-KIrlrChdWk9eEAppipz:-KIrlrChdWk9eEAppiq-:-2061685573) ([raw file](https://github.com/gyrosworkshop/wukong/blob/c9e2a46fa9fd72083c5ae7851fccf9512fbce76d/src/test/QQMusicTest.ts#L9)):*
> ```XML
>         it('La Song base template', async (done) => {
>             try {
>                  const info = await provider.getBaseInfo('003x3eki0Up2RC')
> ```

wrong indent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/17)*

**Comment by Senorsen** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/17)*

**Comment by richard1122** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 7 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/17#-KIrjuRuP-S4vfBzTDxK:-KIrn0LDZhloCvM7LZn4:781398355) ([raw file](https://github.com/gyrosworkshop/wukong/blob/ec61e390569268c6e887909780b77ae396d21a72/package.json#L7)):*
<details><summary><i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>
> 要不要把build和test分开，test时只运行mocha就可以了？
</details>
这里run很快的，正好也可以让CI测试一下编译。还能防止有人忘了编译。

---

*[src/test/QQMusicTest.ts, line 9 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/17#-KIrlrChdWk9eEAppipz:-KIrn50QN04F2OUE1kFc:-467915377) ([raw file](https://github.com/gyrosworkshop/wukong/blob/c9e2a46fa9fd72083c5ae7851fccf9512fbce76d/src/test/QQMusicTest.ts#L9)):*
<details><summary><i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>
> wrong indent?
</details>
fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/17)*

**Comment by Senorsen** [comment]
Reviewed 1 of 2 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/17)*

**Comment by Senorsen** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/17)*

**Pull request merged**
