### PR TITLE
many bug fix.

### PR DESCRIPTION
**Pull request by richard1122**
加入channel时不需要传oldChannelId了（现在会自动从以前的退出）
增加npm start/ debug/ testapi命令
新加入用户默认finish状态为true（开始播放后重置）
增加短线退出channel的逻辑
eventCenter的decorator模式被弃用
eventCenter保存调用者this信息
修正channel最后一个用户无法退出的问题
修正storage对于没有channel的user的崩溃
同步socket.io的room与storage-channel的数据
添加简单的join，leave API测试

---
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/55)

### CODE REVIEW

**Comment by richard1122** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/55)*

**Comment by Leeleo3x** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/55)*

**Comment by Leeleo3x** [comment]
:lgtm:

<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> #### many bug fix\.
> 
> 加入channel时不需要传oldChannelId了（现在会自动从以前的退出）
> 
> 增加npm start/ debug/ testapi命令
> 
> 新加入用户默认finish状态为true（开始播放后重置）
> 
> 增加短线退出channel的逻辑
> 
> eventCenter的decorator模式被弃用
> 
> eventCenter保存调用者this信息
> 
> 修正channel最后一个用户无法退出的问题
> 
> 修正storage对于没有channel的user的崩溃
> 
> 同步socket.io的room与storage-channel的数据
> 
> 添加简单的join，leave API测试
> 
> 
> 
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/55#-:-KJYNbrPF3k82Iyb9Hql:1417088721)*

**Comment by Senorsen** [comment]
test this

**Comment by Senorsen** [comment]
test this with testapi

**Comment by Senorsen** [comment]
test this

**Comment by Senorsen** [comment]
test this

**Comment by Senorsen** [comment]
Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/55)*

**Pull request merged**
