### PR TITLE
Add search for QQ music provider, add decorators.

### PR DESCRIPTION
**Pull request by richard1122**
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/27)

### CODE REVIEW

**Comment by Senorsen** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/providers/QQMusic.ts, line 17 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/27#-KIvnwvvXuQRE30L99ac:-KIvnwvvXuQRE30L99ad:227809095) ([raw file](https://github.com/gyrosworkshop/wukong/blob/b725b4c7d0ece7b2b97c714cbf86124cdffe3355/src/providers/QQMusic.ts#L17)):*
> ```XML
>     @readonly
>     async getSongInfo(songId: string): Promise<Wukong.ISong> {
>         if (!this.songInfoCache.has(songId)) throw new Error('请先搜索再使用')
> ```

呃，必须先搜索再使用，而不能有单独的获取音乐信息的接口？

---

*[src/test/QQMusicTest.ts, line 6 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/27#-KIvnfRPs1SeF_TGg4Au:-KIvnfRPs1SeF_TGg4Av:1031308067) ([raw file](https://github.com/gyrosworkshop/wukong/blob/b725b4c7d0ece7b2b97c714cbf86124cdffe3355/src/test/QQMusicTest.ts#L6)):*
> ```XML
> describe('QQMusicProvider', () => {
>     const provider = new QQMusicProvider()
>     describe('getBaseInfo', () => {
> ```

这个地方的 `getBaseInfo` test 也要删除吧

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/27)*

**Comment by Senorsen** [comment]
Reviewed 3 of 5 files at r1, 1 of 1 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/27)*

**Comment by richard1122** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/providers/QQMusic.ts, line 17 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/27#-KIvnwvvXuQRE30L99ac:-KIvoUxe64mVH75r0D0I:894064477) ([raw file](https://github.com/gyrosworkshop/wukong/blob/b725b4c7d0ece7b2b97c714cbf86124cdffe3355/src/providers/QQMusic.ts#L17)):*
<details><summary><i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>
> 呃，必须先搜索再使用，而不能有单独的获取音乐信息的接口？
</details>
是的，因为逻辑上没法直接获得 songId。而且这是两个不同的接口，不如搜索时候存起来好了。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/27)*

**Comment by Senorsen** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/providers/QQMusic.ts, line 17 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/27#-KIvnwvvXuQRE30L99ac:-KIvp0T6ZCHRZRbXIx9m:-1149503347) ([raw file](https://github.com/gyrosworkshop/wukong/blob/b725b4c7d0ece7b2b97c714cbf86124cdffe3355/src/providers/QQMusic.ts#L17)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 是的，因为逻辑上没法直接获得 songId。而且这是两个不同的接口，不如搜索时候存起来好了。
</details>
我还是感到有些疑虑，应用逻辑上虽然基本如此，但可能存在其他情形：如server重启过，但客户端这边还保留着歌单。
不然加个FIXME好不好？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/27)*

**Comment by richard1122** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/providers/QQMusic.ts, line 17 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/27#-KIvnwvvXuQRE30L99ac:-KIvpKqCxBM291WqzLJg:1443802386) ([raw file](https://github.com/gyrosworkshop/wukong/blob/b725b4c7d0ece7b2b97c714cbf86124cdffe3355/src/providers/QQMusic.ts#L17)):*
<details><summary><i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>
> 我还是感到有些疑虑，应用逻辑上虽然基本如此，但可能存在其他情形：如server重启过，但客户端这边还保留着歌单。
> 不然加个FIXME好不好？
</details>
可以加，但估计不会修的。因为两个接口非常不一致，全都转换一次很不优雅。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/27)*

**Comment by Senorsen** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/27)*

**Pull request merged**
