### PR TITLE
Refact

### PR DESCRIPTION
**Pull request by richard1122**
整理了 join, play, sync, userInfo ,   channelStatus 事件的逻辑。

---
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/46)

### CODE REVIEW

**Comment by Senorsen** [comment]
test this!

**Comment by Senorsen** [comment]
Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46)*

**Comment by Leeleo3x** [comment]
Reviewed 6 of 10 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[README.md, line 75 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBXYCqgpZXL04FlwsV:-KJBXYCqgpZXL04FlwsW:1307327925) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/README.md#L75)):*
> ```Markdown
>     nickname: string
>     listenOnlyMode: boolean
>     gravatar?: string
> ```

Join 为什么要带这么多字段呀。。。

---

*[README.md, line 110 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBSkoXWU52nfeMcwvh:-KJBSkoXWU52nfeMcwvi:-165957543) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/README.md#L110)):*
> ```Markdown
> 
> ### (C -> S) sync
> 表示已经播放完成，不需要数据
> ```

我建议带上elapsed时间，这样这个api还可以在之后有需要的时候用

---

*[src/controllers/ChannelController.ts, line 87 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBYmO5fQRiG8zBgIiL:-KJBYmO5fQRiG8zBgIiM:223686777) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/src/controllers/ChannelController.ts#L87)):*
> ```XML
>         await Utilities.sleep(channel.currentSong.length * 1000)
>         await channel.startCheckUserStatus()
>         if (song !== channel.currentSong) return this.startPlayNextSong(channel)
> ```

这个要不要改成带花括号的 QAQ

---

*[src/controllers/UserController.ts, line 26 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBZSweHB-Kg3pFgSM5:-KJBZSwfrJ-0Vio4N0gQ:1770634980) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/src/controllers/UserController.ts#L26)):*
> ```XML
> 
>     private shouldBroadcastUserUpdate(userId: string) {
>         eventCenter.dispatchEmplace<string>(Constants.Events.SHOULD_BROADCAST_USER_UPDATE, Storage.getChannelByUser(userId).channelId)
> ```

这一行好长呀。。。

---

*[src/models/Channel.ts, line 41 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBZodO-4e_Posqo8th:-KJBZodO-4e_Posqo8ti:1116051863) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/src/models/Channel.ts#L41)):*
> ```XML
>     }
> 
>     async startCheckUserStatus(): Promise<void> {
> ```

吼吼呀。。。提一个不成熟的小意见。。。我不确定这段代码是不是应该移到controller里面。。。

---

*[src/models/Channel.ts, line 48 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBUmxHIDRmUVRFA4GS:-KJBUmxHIDRmUVRFA4GT:-1337009291) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/src/models/Channel.ts#L48)):*
> ```XML
>     }
> 
>     @readonly
> ```

不太确定这个是否有意义。。。

---

*[src/routers/Router.ts, line 20 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJB_U40N_3-XlHWibAB:-KJB_U40N_3-XlHWibAC:-211970061) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/src/routers/Router.ts#L20)):*
> ```XML
>                 this.userController.updateSongsList(socket.id, songsEvent.songs)
>             })
>             socket.on('sync', () => {
> ```

我突然想到sync是不是还是要吧song传过来，这样的话如果客户端卡了应该不会出问题？。。。

---

*[src/routers/Router.ts, line 38 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBVvUyNNs4C7ADc9gN:-KJBVvUzcSF3z0kLSJki:2111493988) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/src/routers/Router.ts#L38)):*
> ```XML
>     private onUserEvent(event: Event<Wukong.EventUser<any>>) {
>         console.log(event)
>         this.io.sockets.sockets[event.data.userId].emit(event.data.event, event.data.data)
> ```

这一行是不是有点长。。。

---

*[types/type.d.ts, line 32 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJB_pLXsIJZLJa_eqQB:-KJB_pLXsIJZLJa_eqQC:1779059606) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/types/type.d.ts#L32)):*
> ```XML
>         nickname: string
>         gravatar?: string
>         listenOnlyMode: boolean
> ```

嗯嗯。。和文档里面说的。。。这些需要传吗？。。。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46)*

**Comment by richard1122** [comment]
*[README.md, line 75 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBXYCqgpZXL04FlwsV:-KJBfNzDgv1NG3Qpzk7D:-1474229549) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/README.md#L75)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> Join 为什么要带这么多字段呀。。。
</details>
join 这里在考虑考虑吧，我觉得在没有个人信息时候最好还是不用能join，否则增加很大复杂程度。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46)*

**Comment by richard1122** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[README.md, line 110 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBSkoXWU52nfeMcwvh:-KJBfbXiN8U6G87ZcvD9:-71205253) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/README.md#L110)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 我建议带上elapsed时间，这样这个api还可以在之后有需要的时候用
</details>
可以在有需要时候加吧。。。。。

---

*[src/controllers/ChannelController.ts, line 87 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBYmO5fQRiG8zBgIiL:-KJBfi53GNamIwsx8cVd:-467915377) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/src/controllers/ChannelController.ts#L87)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 这个要不要改成带花括号的 QAQ
</details>
fixed

---

*[src/controllers/UserController.ts, line 26 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBZSweHB-Kg3pFgSM5:-KJBfmBrLFOgvuovGjoU:-467915377) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/src/controllers/UserController.ts#L26)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 这一行好长呀。。。
</details>
fixed

---

*[src/models/Channel.ts, line 48 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBUmxHIDRmUVRFA4GS:-KJBfsgJ1CQqbHcP2Jad:251411729) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/src/models/Channel.ts#L48)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 不太确定这个是否有意义。。。
</details>
我加了下花括号，你是不确定这段代码运行对不对？

---

*[src/routers/Router.ts, line 20 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJB_U40N_3-XlHWibAB:-KJBfxJ20tUIT8om8shv:1458899301) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/src/routers/Router.ts#L20)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 我突然想到sync是不是还是要吧song传过来，这样的话如果客户端卡了应该不会出问题？。。。
</details>
如果提交了song我们要怎么处理呢？是把这个请求抛弃掉还是？。。我也觉得应该需要的，我加一下

---

*[src/routers/Router.ts, line 38 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBVvUyNNs4C7ADc9gN:-KJBgABQKoAxtZt4B3hD:-467915377) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/src/routers/Router.ts#L38)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 这一行是不是有点长。。。
</details>
fixed

---

*[types/type.d.ts, line 32 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJB_pLXsIJZLJa_eqQB:-KJBgBWEEFsLWcDiaLnj:-1393332700) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/types/type.d.ts#L32)):*
<details><summary><i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>
> 嗯嗯。。和文档里面说的。。。这些需要传吗？。。。
</details>
你是指 listenOnlyMode，今天跟lb讨论了下，还是设置一个开关，而不是把客户端列表清空

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46)*

**Comment by Senorsen** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[README.md, line 110 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJBSkoXWU52nfeMcwvh:-KJBkjF-ctSsdZEZ5n7r:-1534646135) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/README.md#L110)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 可以在有需要时候加吧。。。。。
</details>
我也觉得可以加

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46)*

**Comment by Senorsen** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/routers/Router.ts, line 20 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJB_U40N_3-XlHWibAB:-KJBkwWa6DlWVZX8nims:1311507294) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/src/routers/Router.ts#L20)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 如果提交了song我们要怎么处理呢？是把这个请求抛弃掉还是？。。我也觉得应该需要的，我加一下
</details>
应该是不理会错误的客户端吧，或者友好的告诉客户端现在正在播放的曲目？

---

*[types/type.d.ts, line 32 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46#-KJB_pLXsIJZLJa_eqQB:-KJBlAGNy82XYzC4C_nZ:-323914176) ([raw file](https://github.com/gyrosworkshop/wukong/blob/7e498828dc7851d94934e7d977aa6e7fdf13a188/types/type.d.ts#L32)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 你是指 listenOnlyMode，今天跟lb讨论了下，还是设置一个开关，而不是把客户端列表清空
</details>
`listenOnlyMode`是个怎样的模式？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/46)*

**Pull request merged**
