### PR TITLE
Add search part.

### PR DESCRIPTION
**Pull request by Leeleo3x**
- Add search API.
- Modify documents.

---
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/50)

### CODE REVIEW

**Comment by richard1122** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/providers/base.ts, line 11 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/50#-KJE7aZPVqZp0-rU-QOV:-KJE7aZQ4czq6kNQb9Nd:1984022453) ([raw file](https://github.com/gyrosworkshop/wukong/blob/05cbe898d73f6dbee4dc1beb5a61ca46d2a56976/src/providers/base.ts#L11)):*
> ```XML
>      * set provider name, eg: netease-cloud-music
>      */
>     static providerName: string
> ```

这里为什么是 static 的？ 每个provider 应该有不同的名字吧？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/50)*

**Comment by richard1122** [comment]
Reviewed 5 of 9 files at r1.
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/50)*

**Comment by Senorsen** [comment]
Review status: 4 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/providers/base.ts, line 11 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/50#-KJE7aZPVqZp0-rU-QOV:-KJEuz-gGrcP6K7o4VQr:473487269) ([raw file](https://github.com/gyrosworkshop/wukong/blob/05cbe898d73f6dbee4dc1beb5a61ca46d2a56976/src/providers/base.ts#L11)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 这里为什么是 static 的？ 每个provider 应该有不同的名字吧？
</details>
他这个应该是正确的（通过了刚刚加上的`siteId`的测试）

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/50)*

**Comment by richard1122** [comment]
Reviewed 4 of 9 files at r1, 3 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/50)*

**Comment by Leeleo3x** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/providers/base.ts, line 11 \[r1\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/50#-KJE7aZPVqZp0-rU-QOV:-KJGEhaYCrgVBpAQUZRR:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/05cbe898d73f6dbee4dc1beb5a61ca46d2a56976/src/providers/base.ts#L11)):*
<details><summary><i>Previously, Senorsen (Zhang Sen) wrote…</i></summary>
> 他这个应该是正确的（通过了刚刚加上的`siteId`的测试）
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/50)*

**Comment by richard1122** [comment]
@Senorsen 你有一个 未解决的讨论，你点一下然后合并吧。

**Comment by Senorsen** [comment]
Reviewed 8 of 9 files at r1, 3 of 5 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/50)*

**Pull request merged**
