### PR TITLE
Down Vote

### PR DESCRIPTION
**Pull request by Leeleo3x**
This change is [Reviewable](https://reviewable.io/reviews/gyrosworkshop/wukong/85)

### CODE REVIEW

**Comment by richard1122** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/models/Channel.ts, line 89 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/85#-KLA2WsGsC4AQhc3Uhit:-KLA2WsHLUv89Bqak8qP:-1723080824) ([raw file](https://github.com/gyrosworkshop/wukong/blob/98f300944d318c18eb7c996bfee967b78f3ff3f0/src/models/Channel.ts#L89)):*
> ```XML
>             return false
>         }
>         const activeDownVoteUserList = this.userList.map(user => user.userId).filter((userId) => this.downVoteUserList.has(userId))
> ```

https://lodash.com/docs#xorBy 可以用这个函数。。不用这么麻烦。。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/85)*

**Comment by richard1122** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/models/Channel.ts, line 92 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/85#-KLA2dgZhvRpsEKYfYI8:-KLA2dgZhvRpsEKYfYI9:193648610) ([raw file](https://github.com/gyrosworkshop/wukong/blob/98f300944d318c18eb7c996bfee967b78f3ff3f0/src/models/Channel.ts#L92)):*
> ```XML
>         const downVoteUserCount = activeDownVoteUserList.length
>         const userCount = this.userList.length
>         return downVoteUserCount >= Math.ceil(userCount * 2 / 3)
> ```

这个数值太大了吧。。。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/85)*

**Comment by richard1122** [comment]
Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/85)*

**Comment by Leeleo3x** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/models/Channel.ts, line 89 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/85#-KLA2WsGsC4AQhc3Uhit:-KLA9p_uGbIplJMQ92Ku:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/98f300944d318c18eb7c996bfee967b78f3ff3f0/src/models/Channel.ts#L89)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> https://lodash.com/docs#xorBy 可以用这个函数。。不用这么麻烦。。
</details>
Done.

---

*[src/models/Channel.ts, line 92 \[r2\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/85#-KLA2dgZhvRpsEKYfYI8:-KLABXKg7-qdtXZmzVz_:-499146009) ([raw file](https://github.com/gyrosworkshop/wukong/blob/98f300944d318c18eb7c996bfee967b78f3ff3f0/src/models/Channel.ts#L92)):*
<details><summary><i>Previously, richard1122 (richard) wrote…</i></summary>
> 这个数值太大了吧。。。
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/85)*

**Comment by richard1122** [comment]
Reviewed 1 of 1 files at r4.
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/85)*

**Comment by richard1122** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/models/Channel.ts, line 45 \[r4\]](https://reviewable.io:443/reviews/gyrosworkshop/wukong/85#-KLH6jAAH157OHrxAHfd:-KLH6jAAH157OHrxAHfe:-521361552) ([raw file](https://github.com/gyrosworkshop/wukong/blob/ba507f6067c2d1dc303f74db6313fdfee924d054/src/models/Channel.ts#L45)):*
> ```XML
>         if (!this.currentSong) {
>             this.userList.forEach(it => it.finished = true)
>             return undefined
> ```

return 和 return undefined 应该是一个意思吧。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/85)*

**Comment by richard1122** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gyrosworkshop/wukong/85)*

**Pull request merged**
